// Writes extension/flags.js: inline SVG flags for the countries residential pools
// are usually bought in. Others fall back to a code chip. Run: node scripts/flags.mjs
import fs from 'node:fs';

const CODES = 'IN US GB CA AU DE AE SG FR NL JP BR ES IT MX ID TR PK BD PH VN TH ZA NG EG SA PL RU UA KR HK'.split(' ');
const entries = [];
for (const code of CODES) {
  const src = fs.readFileSync(`node_modules/country-flag-icons/string/3x2/${code}.js`, 'utf8');
  const svg = src.match(/export default '(.*)';?\s*$/s)?.[1];
  if (!svg) throw new Error(`Couldn't read ${code}`);
  entries.push(`  ${code}: '${svg}',`);
}
fs.writeFileSync('extension/flags.js', `// Generated by scripts/flags.mjs. Do not edit.\nexport const FLAGS = {\n${entries.join('\n')}\n};\n`);
console.log(`Wrote extension/flags.js (${entries.length} flags)`);
